### ISSUE TITLE
Error: attempt to index local 'info' (a nil value)

### ISSUE THREAD

**Issue by jetm** [ii14/onedark.nvim#1]
Hi,

Thank you for this plugin.

I am using the `NVIM v0.5.0-dev+1405-g2f0e5e7e6` and I am getting this error:
```
Error detected while processing .../onedark.nvim/colors/onedark.vim:
line    1:
E5108: Error executing lua .../share/nvim/runtime/lua/vim/_meta.lua:21: attempt to index local 'info' (a nil value)
```
It was not happening with a previous nightly nvim version.

**Comment by ii14** [comment]
Thanks, it should be fixed now.

**Comment by jetm** [comment]
@ii14 It works. Thanks!
