### ISSUE TITLE
Can't override background

### ISSUE THREAD

**Issue by SquiffyK7** [ii14/onedark.nvim#2]
Hello

Thanks for the port.

I can't seem to override the background colour. The best I can do to make my vim background match my terminal background is set black to NONE:
```
vim.g.onedark_color_overrides = {
  black = { gui = "NONE", cterm = "NONE", cterm16 = "NONE" },
}
```
but this totally removes the black colour, which I want to keep for e.g. highlighted text.

**Comment by ii14** [comment]
```vim
autocmd ColorScheme * hi Normal guibg=NONE ctermbg=NONE
```
or
```lua
vim.api.nvim_create_autocmd('ColorScheme', { command = 'hi Normal guibg=NONE ctermbg=NONE' })
```

**Comment by SquiffyK7** [comment]
Excellent that works! Thanks @ii14
